project:
  type: website
  output-dir: docs
website:
  title: "blog"
  site-url: https://hafez-ahmad.github.io/site
  description: "My personal blog"
  navbar:
    right:
      - text: About Me
        href: about.qmd
      - text: CV
        href: cv/index.qmd
      - text: News
        href: news/index.qmd
      - text: Notebook
        href: Notebook/index.qmd
      - text: Projects
        href: projects/index.qmd
      - text: Teaching
        href: teaching/index.qmd
      - text: Blog
        href: posts/index.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    additional-css: beautiful.css

editor: visual

path: C:\Program Files\Quarto\bin

