---
title: "News"
description: "Latest updates and announcements"
format: 
  html:
    css: styles.css
    theme: 
      light: flatly
      dark: darkly
---

# News

## April 30, 2025
- **New Project Launched**: We are excited to announce the launch of a new project on "Integrated Coastal Water Monitoring and Modeling."

## April 25, 2025
- **New Blog Post**: Check out our latest blog post on "How to Make Dynamic Maps with Python."

## April 26, 2025
- **New Research Published**: Our latest research on Ocean optics modeling has been published in the Journal of Environmental earth sciences.
- **Upcoming Workshop**: Join us for a workshop on "Dynamic Mapping with Python" on May 15, 2025.
- **PhD Milestone**: I am thrilled to announce that I have passed my PhD candidacy exam and am now officially a PhD candidate!

## April 20, 2025
- **Website Update**: The blog has been updated with new posts on PCA and Machine Learning in Oceanography.

## April 20, 2024
- **Conference Update**:  My Conference abstract has been accepted in ASLO conference, North Carolina, USA

## January 01, 2024
- **Education Update**:  I have started my PhD at Mississippi State University

## January 01, 2022
- **Education Update**:  I have started my MS at Mississippi State University


